import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from 'react';

const inter = Inter({ subsets: ["latin"] });

interface FormData {
  title:string
  content:string
  id:string
}

export default function Home() {

  const [form, setForm] = useState<FormData>({title:"", content:"", id:""});

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1 className='text-center font-bold text-2xl mt-4'>Notes</h1>
        <form
          onSubmit={(e) => {
            e.preventDefault();
          }}
          className='w-auto min-w-[25%] max-w-min mx-auto space-y-6 flex flex-col items-stretch'
        >
          <input
            type='text'
            placeholder='Title'
            value={form.title}
            onChange={(e) => setForm({ ...form, title: e.target.value })}
            className='border-2 rounded border-gray-600 p-1'
          />
          <textarea
            placeholder='Content'
            value={form.content}
            onChange={(e) => setForm({ ...form, content: e.target.value })}
            className='border-2 rounded border-gray-600 p-1'
          />
          <button type="submit" className="bg-blue-500 text-white rounded-sm">Add +</button>
        </form>
      </div>
    </>
  );
}
